stages:
  - test
  - deploy

UnitTest:
  image: python:3.6
  stage: test
  before_script:
    - pip3 install -r requirements.txt
    - python3 manage.py makemigrations
  script:
    - python3 manage.py migrate
publish:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=dementorjofil --api-key=$HEROKU_API_KEY
  only:
    - master
