# Generated by Django 2.0.2 on 2019-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseDementor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofoliodata',
            name='description',
            field=models.TextField(),
        ),
    ]
