# Generated by Django 2.2.2 on 2019-06-04 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseDementor', '0002_auto_20190604_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatAmIDoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today)),
                ('update', models.CharField(max_length=200)),
            ],
        ),
    ]
