# Generated by Django 2.2.2 on 2019-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseDementor', '0003_whatamidoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofoliodata',
            name='image',
            field=models.TextField(max_length=1000),
        ),
    ]
